<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PvPreiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PvPreiseRepository extends EntityRepository
{
	 public function findByPreisversionen($id)
	    {
	        $arr = $this->getEntityManager()
	            ->createQuery( 'SELECT pvp FROM AppBundle:PvPreise pvp WHERE pvp.pvp_pv_id = '.$id)
	            ->getResult();
	      	
            return $arr;
	    }
}
